# -*- coding: utf-8 -*-
"""Break and continue

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18J1ZZWmY-QxZpZtIaen0egX-D7BMwyms
"""

# The break statement enables a program to skip over a part of the code. A break
#statement terminates the very loop it lies within.
#Break means to leave the loop while continue means to leave the iteration.
for i in range(12):
  print("5 *", i+1, "=",5*(i+1))
  if(i==3):
    print("end of loop")
    break

for i in range(2,-7,-2):
  print(i)

for i in range(12):
  if(i==3):
    print("skip")
    continue
    #Confusion
  print("5 *", i+1, "=",5*(i+1))

#Emulation of Do while loop
while True:
  print(i)
  if(i%100==0):
    break
    #infinite loop
  i=i+1

i=int(input())
while True:
  print(i)
  if(i<0):
    break
    #infinite loop
  i=i+1