# -*- coding: utf-8 -*-
"""Day 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n552vbP3PhtrOAONgtLiLM-GV0PdL0er
"""

print ("learning about comments")

#comments
print (2*2)

type (5)

"""for multi line comments"""

print (type(2))

x=2
print(type(x))



int(a)
a=2
str (b)
str (a)

print ("I am learning comments")
#print(1)

#see about datatypes
#conversion of datatypes,

cat="z"
print (cat)

cat="Z"
print (Cat)

var1="dog"

type(2.7)

x=False
type(x)

print(type(7))

x=2.7
x=int(x)
print (x)

y=2
print (y)
print (type(y))
y=str(2)
print(y)
print(type(y))

a="2"
b=2
print (type(a))
print(type(b))

a="4"
b=4
print (b+4)

a=2
b=7.7
print (a+b)

print('hello')

name="basrah"
name="sadaf"
print(name)

name="Tony Stark"
Age=51
Tonyisagenius = True
print(name)
print(Age)
print(True)
print(type(True))

name="Tony Stark"
Age=51
Tony_is_genius=True
print(name)
print (Age)
print()

name="Tony"
Age=51
print(name)

name=input('what is your name?')
print(name)

name=input('what is your name?')
print('hello ' + name) #concatenation