# -*- coding: utf-8 -*-
"""Day 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9URr9B4UB-MOSdp-3-_is6aurmG1xC8
"""

print ("Hello world")
print ("World of coding")
## Comments

print (1*8)

print(9*9)

print("6*6")

print(6*6)

abcd=1
print (abcd)

abc1=2
print (abc1)

def1= 6
print =(def1)

def66=6
print = (def66)

print=("122")