# -*- coding: utf-8 -*-
"""Function Arguments

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rUkcErqPue9zqJ7skTOHlhJkko1IP5YD
"""

#There are four types of argurments that we can provide in a function:
#Default Arguments
#Keyword Arguments
#Variable length Arguments
#Required Arguments

def Average(a=2,b):
  print("The average is ", (a+b)/2)
Average(2)
#a and b are required arguments here.
#2 and 7 are default arguments.
Average(b=7,a=2)
#keyword arguments (we gave the value of a and b ourselves)

def avg(*numbers):
  print(type(numbers)) #taking it as tuple
  sum = 0
  for i in numbers:
    sum = sum+i
    print('average is:',sum/len(numbers))
avg(5,6)
#Doubt
def avg(**numbers1):
 print(type(numbers1)) #Should take it as a dictionary.
sum = 0
  for i in numbers1:
    sum = sum+i
    print('average is:',sum/len(numbers1))
    avg(7,8)
    #Confusion

numbers = [3,6,9]

for i in numbers:
  print("The value of i is: ",i)







#return will save the value in a particular variable. but you'll have to define the variable.