# -*- coding: utf-8 -*-
"""Functions

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1USkX7SjoobqaQJBYb06_Sl9fkOvEhwPJ
"""

# A function is a block of code that performs a specific task whenever it is called.
#Two types of functions:
#Built in functions
#eg, min(), max(), len(), sum(), type(), range(), dict(), list(), tuple(), set(), print(), etc.
#User defined functions
# Rules to naming a function is similar to that of naming a variable.
def calculate(a,b):
  Operation= (a*b)/(a+b)
  print(Operation)
a = 9
b = 8
operation = (a*b)/(a+b)
print(operation)
c = 2
d=2
calculate(c,d)
print(gmean2)
# Doubt: Why is 1.555 being printed?

def Greater(a,b):
  if(a>b):
    print("First number is greater")
  else:
    print("Second number is greater or equal")
Greater(7,7)

def Lesser(a,b):
 pass #no error thrown