# -*- coding: utf-8 -*-
"""If Else

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mej1PiwUNDM4J6HT9p0UyoqEljaz9TYW
"""

a=int(input("Enter your age"))
print("your age is", a)
if(a>=18):
  print("You can drive") #indentation
  print(1)
else:
    print("You can't drive")
    #conditional operators, <,>,>=,>=,==,!=(not equal to)
    print("hahaha")
    print(a>18)
    print(a==18)
    print(a<18)
    print(a>=18)

PizzaPrice=220
Budget=200
if(PizzaPrice<=Budget):
  print('Have a party')
else:
  print("Do not have a party")

num=int(input("Enter the number"))
if(num<0):
  print("Number is negative")
elif(num==0):
 print("Number is equal to zero.")
elif(num==7 or 2):
  print("Lucky number")


else:
  print("Number is positive")

#Nested if else
num=8
if(num<0):
  print("Number is negative")
elif(num>0):
  if(num<=10):
    print("Number is between 1-10")  #Level of indent
  else:
    print('Number is grater than 10')
else:
  print("number is zero")