# -*- coding: utf-8 -*-
"""Lists

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nvOLNg0iRFv4ZehVFlUZI_aSShtj26tr
"""

list = [11,781,2,9,3,1]
print(list)
print(type(list))
print(list[0])
list.append(4)
print(list)
list.sort()
print(list)
list.sort(reverse=True)
print(list)
list.reverse()
print(list)
print(list.index(781))
m=list
m[0]=4
print(m)
m=list.copy()
m[0]=7
print(m)
list.insert(1,78)
print(list)
list1 = [1,2,3]
list.extend(list1) #add list1 in list
print(list)
list2= list + list1
print(list2)
print(list[-3])



#lists are mutable meaning they are changaebale, we can alter them after creation.t



marks = [1,2,3,"eee", True, ]
print(marks)
print(marks[4])

print(list[0])

print(list[-3]) #Confusion in the output

if 's' in 'sadaf':
 print("yes")
else:
  print("no")

marks=[1,2,3,4,5]
print(marks[2:4])
print(marks[2:-2])
print(marks[2:3:1])
list=[4,9]
print(list)

list4 = [i*i for i in range (8)]
print(list4)
list6 = [i*i for i in range (20) if i%2==0]
print(list6)