# -*- coding: utf-8 -*-
"""Match Case Statements

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MPZSRr_xcturn_4XoP-fBD89pkiROYsc
"""

# A match statement will compare a given variable's value to diferent values to different shapes
#,also reffered to as the pattern. The main idea is to keep on comparing the variable with
# all the present patterns until it fits into one.
#The match case consists of three main entities:
#The match Keyword
#One or more case clauses
#Expression for each case.
x=int(input())
#x is the variable to match
match x:
  # if x is 0
  case 0:
    print("x is zero")
    #case with if condition
  case 4:
    print(" case is 4")
      # Empty case with if condition
  case _ if x<10:
    print("x is <10")
        #default case (will only be matched if the above cases were not matched)
# so it is basically just an else:
  case _:
    print(x)
    #can have as many default cases.