# -*- coding: utf-8 -*-
"""Operation on Tuples

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UnooaIDF1yVQdtMCKhDjFz-zzD-hgP7b
"""

tuple1 = (1,2,3,4,5,6,7)
numbers = list(tuple1)
numbers.append(8)
numbers.pop(3)
numbers[2]=10
tuple1 = tuple(numbers)
print(tuple1)

tuple2 = (1,2,3)
tuple3 = (4,5,6)
print(tuple2.count(1))
print(tuple2.count) #Doubt
print(tuple2.index(1))
print(tuple2.index(1,0,1))
tuple4 = tuple2 + tuple3
print(tuple4)
print (len(tuple4))



