# -*- coding: utf-8 -*-
"""Python Day 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d3W2a4XM64jcbs-BvQUr0nSY5TqB2dyV
"""

a=123
b='a'
c=True
d=None
e=2.3
f=complex(2,3)
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))

"""Lists are the collection of different data types. These are mutable and
can be modified after creation."""
List1 = [2,"a", 9.9,]
print(List1)

""" tuple is alomst the same as that of list. It too is an orderede collection
of data with elements seperated by a comma and enclosed within parantheses.
Tuples are immutable and can not be modified after creation."""
tuple1=('a', 2,(1,2))
print(tuple1)

## Mapped dat: dictionary
""" A dictionary is an unordered collection of data containing a 'key value
pairs'. The key value pairs are enclosed within curly brackets. """
dict1= {"name":"Sadaf", "age":23, "coder":True}
print(dict1)

## In python, everything's an object.