# -*- coding: utf-8 -*-
"""Python Day 7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_qMv5cnVWOXpTa6aYhfPWJ0Wr3NkJpcb
"""

# Operators: +, -, *, /, //(floor division operator),%(modulus),**(exponential)
print(2+9)
print(2-9)
print(2*9)
print(2/9)
print(2//9)
print(2%9)
print(2**9)

## Exercise: Create a calculator capable of performing addition, subtraction, multiplication,
## and division operations on two numbers. Your program should format the
## output in a readable manner.
num1 = 5
num2 = 4
ans1 = 5+4
ans2 = 5-4
ans3 = 5*4
ans4 = 5/4
print("addition of 5 and 4 is", ans1)
print("subtraction of 5 and 4 is", ans2)
print("Multiplication of 5 and 4 is", ans3)
print("Division of 5 and 4 is", ans4)