# -*- coding: utf-8 -*-
"""python day 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ajCB5y-QfYHJAnjPTb0NPKZT1tRdOs0G
"""

var='True'
print(var)
print(type(var))

x=True

var=True
print(var)
print(type(var))



x= this is a string

a1=False
a2='False'

#why do we need lists
#used when we have huge number of data. sq brackets. commas have to be used.
myFirstList = [1,2,3,5,7]
print(myFirstList)
print(type(myFirstList))

x=1,2,3,4
print(x)

list=['sadaf','Ajaz', 'Baba', 1]
print(list)
print(type(list))

x=1, 2, "xyz"
print(x)
len(x)

#length of list
len(list)

