# -*- coding: utf-8 -*-
"""python day 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TyxzubvZKgYR4e5m8cYjxzN_IDdG7eyP
"""

Marks = [5,3,4,7,8,9]
#python has 0 based indexing, say for example if he want to access 3rd element, its index will be 2.
print(Marks[2])

#lets try doing the same with variables
Marks1 = (5,3,4,7,8,9)
print(Marks1[2])
#if I try asking for 6th elemet here, it will throw me an error because there are only 5 elemets here.
#element wyth 6th index means 7th element.

"""changing elements of a list.
For this, we use = (assignment operator)"""
Marks = [5,3,4,7,8,9]
Marks[0] = 2
print(Marks)
#We'll get the updated list.
#Tadaaaaaa

#Range of values
# : is used, starting index is included but ending index is not included.
Marks = [5,3,4,7,8,9]
print(Marks[2:4])

# Appending the elements.
Marks = [5,3,4,7,8,9]
Marks.append(6)
print(Marks)

# For entering a value