# -*- coding: utf-8 -*-
"""Self practice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cTm6SPto6vh9ydNnJ-XYFVIKsmIEzToz
"""

a=2
b=4
print(a+b)

a=9
b=7
average=(a+b)/2
print( average)

Number1=input("x")
Number2=input("y")
average=(x+y)/2
print(average)