# -*- coding: utf-8 -*-
"""Self Practice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pBxNdDm6YPaAOaUF-LKvXQq1VcDMTQZU
"""

#Create a python program capable of greeting you with Good Morning,
#Good Afternoon, and Good Evening. Your program should use time module
#to get the current hour.
import time
Recenttime = time.strftime('%H:%M:%S')
a= "Sir"
print (Recenttime)
recenttime=int(time.strftime('%H'))
if 4<=recenttime<12:
  print("Good Morning",a)
elif 12<=recenttime<4:
  print("Good After Noon",a)
else:
   print("Good Evening", a)