# -*- coding: utf-8 -*-
"""Strings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wl9_9nUWP2wCFYTVzEpeTJHJz615a1Mq
"""

# A string is essentially a sequence or array of textual data. used when working with unicode characters
name='Peerzada Sadaf Ajaz Baba'
Gender="Female"
print('hello '+name)

#escape sequence character
statement= 'He said, \'I want to eat an apple.\''
print(statement)
statement2= 'She said,"I want to eat an apple"'
print(statement2)
Statement3="""hi sadaf
What did I ever do to get this
kind of behaviour?""" # used for multi line string
print(Statement3)

print(name[0]) #index name variable
print(name[1])
print(name[2])
print(name[3])
print(name[4])
print(name[5]) #since no character is at 5th index

###Looping through the string
# we can loop through strings using a for loop like this:

for character in name:
  print(character)

for character in statement:
  print(character)

Name1="Peerzada, Sadaf, Ajaz, Baba"
print(Name1[0:8])