# -*- coding: utf-8 -*-
"""String Slicing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CPdjguBlVLST-zpkB4Q-o7Uj41KafjNU
"""

Name = "Peerzada, Sadaf, Ajaz, Baba"
print(Name[0:8])

#length can be found using len()
Name = "Peerzada, Sadaf, Ajaz, Baba"

print(len(Name))

Fruit='Mango'
print('Mango is a ',len(Fruit), 'letter word.' )
print(Fruit[1:3])
print(Fruit[:3])
print(Fruit[0:3])
print(Fruit[1:])
print(Fruit[:])
print(Fruit[0:-3])
print(Fruit[-1:-3])
#Try understanding it again.(Day12)

nm = "Harry"

print(nm[-4:-2])