# -*- coding: utf-8 -*-
"""Taking user input

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jDJNLS84kYmZY6tWbJv2m9WiURrFMXA3
"""

#syntax: variable=input()
a= input( "enter your name here")
print("my name is ",a)

x= input ('Enter first number') #even if a number is given in an input, its taken as a string
y= input ('Enter second number')
print(int(x)+int(y))

a=10
if a:
  print(a)

a=0
if a:
  print(a)

a=-5
if a:
  print(a)

a=9<8
if a:
  print(a)

a=8<9
if a:
  print(a)