# -*- coding: utf-8 -*-
"""Tuples

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VMMUFI5-REXQbbuoCKWGs97-j_FLth_Y
"""

#s=(1,2,3,4,5)
#s.append()
#wont append because tuples are immutable.

tup = (1,2,3)
print(type(tup), tup)
print(tup[0])

tupp = (1)
print(type(tupp))

if 1 in tup:
  print('yes')
else:
  print('no')

tup2 = tup[1:2] #slicing
print(tup2)