# -*- coding: utf-8 -*-
"""Typecasting

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/162PMzuIUar2gygqumRzgNCmPrucTkf7D
"""

"""The conversion of one data type into the other data type is known
as type casting in python or type conversion in python.
Python supports a wide variety of functions or methods like: int(),
float(),str(), ord(), hex(), oct(), tuple(), set(), list(), dict(),
etc. for the typecasting in python."""
"""Two types of type casting:
Explicit conversion (explicit type casting)(that we as a programmer do)
Implicit Conversion (implicit type casting)(that puthon does)"""
a="1"
b="2"
print(a+b)
print(int(a)+int(b))

string = '15'
number=7
string=int(15)
sum= number+string
print("the sum of two numbers is", sum)

"""Data types in python do not have the same level i.e;
ordering of data types is not the same in python. some have higher
order, some have lower orser. While performing any operation with different
data types, one of the variables data type will be changed to the higher
data type by the python interpreter itself.
Python converts a smaller data type to a higher data type to prevent data loss."""

c=1.2
b=3
print(c+b)
# here converted the integer into the float