# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bKhd8tsGLpeqQr3DoLzk2gDhgrjwlcRi
"""

#variables are like containers that store data in RAM. the adress of 1 in memory has given to a.
a=1234567890
b="Jude St. Francis"
c=None
print(b)
print(a)
print(type(c))
print("The type of c is", type(c))

#see what truncated means