# -*- coding: utf-8 -*-
"""While loop

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dgq0P7HRIgOWx6ZEjPQCYLv0Zx8Ms_TB
"""

# As the name suggests, while loops execute statements while the condition
  # is true. As soon as the condition becomes False, the interpreter comes out
  #of the while loop.
i=0
while(i<3):
 print(i)
 i=i+1

i=int(input())
 while(i<=3):
  print(i)
  i=i+1

count=5  #decreamenting while loop
while (count>0):
  print(count)
  count=count-1

#Infinite loop count=5
#while (count>0):
  #print(count)
  #count=count+1

#else can also be used with while loop
count=int(input())
while (count>0):
  print(count)
  count=count-1
else:
  print("Else condition")
  #As soon as the while loop becomes false; the conditiuon in else is fulfilled.

#Emulate Do while loop.
#So basically DO whilw loop executes at least one even if the condition is false
#do{
    #loop body
#}while (condition)
#used in other programming languages

i=8
while (i<7):
  print(i)
else:
   print(i)
   #try doing it again after learning "Break and Continue"

